# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\cccd_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(748, 556)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"gridline-color: rgb(0, 255, 255);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 480, 851, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 120, 821, 41))
        self.line_2.setStyleSheet("selection-color: rgb(85, 170, 255);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 85, 831, 31))
        self.line_3.setStyleSheet("color: rgb(0, 85, 255);")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 0, 521, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 170, 255);\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 50, 401, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 111, 91))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(".\\../../Downloads/th.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 471, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 500, 501, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 170, 711, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    padding-left: 10px;\n"
"   \n"
"\n"
"}\n"
"QPushButton#pushButton{\n"
"    border: 1px solid #63b8ff;\n"
"    background-color: rgb(255, 255, 255);\n"
"   \n"
"}\n"
"\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 240, 711, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    padding-left: 10px;\n"
"}\n"
"QPushButton#pushButton_2{\n"
"    border: 1px solid #63b8ff;\n"
"    background-color: rgb(255, 255, 255);\n"
"   \n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 320, 711, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    padding-left: 10px;\n"
"}\n"
"QPushButton#pushButton_3{\n"
"   border: 1px solid #63b8ff;\n"
"    background-color: rgb(255, 255, 255);\n"
"   \n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 400, 711, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    padding-left: 10px;\n"
"}\n"
"QPushButton#pushButton_4{\n"
"   border: 1px solid #63b8ff;\n"
"    background-color: rgb(255, 255, 255);\n"
"   \n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(700, 100, 41, 31))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(".\\../../Downloads/home-xl.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionlogo = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../../Downloads/th.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionlogo.setIcon(icon)
        self.actionlogo.setObjectName("actionlogo")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Identification Card Examination "))
        self.label_2.setText(_translate("MainWindow", "Thiết bị lấy mẫu và xác thực CCCD"))
        self.label_4.setText(_translate("MainWindow", "Menu Chức năng Giám định"))
        self.label_5.setText(_translate("MainWindow", "Lựa chọn thao tác giám định cần thực hiện "))
        self.pushButton.setText(_translate("MainWindow", "1) Kiểm tra đặc điểm kỹ thuật bảo vệ : Cấp Phổ thông "))
        self.pushButton_2.setText(_translate("MainWindow", "2) Kiểm tra đặc điểm kỹ thuật bảo vệ : Cấp Phòng thí nghiệm "))
        self.pushButton_3.setText(_translate("MainWindow", "3) Kiểm tra đặc điểm kỹ thuật bảo vệ : Phương pháp in  "))
        self.pushButton_4.setText(_translate("MainWindow", "4) Kiểm tra chuẩn đoán nhanh có xác thực thông tin "))
        self.actionlogo.setText(_translate("MainWindow", "logo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
